1. Scrape the details of most viewed videos on YouTube from Wikipedia. Url
= https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details: A)
Rank
B) Name
C) Artist
D) Upload date
E) Views

In [1]:
!pip install selenium

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: selenium in c:\users\dell\appdata\roaming\python\python39\site-packages (4.12.0)
Requirement already satisfied: trio~=0.17 in c:\users\dell\appdata\roaming\python\python39\site-packages (from selenium) (0.22.2)
Requirement already satisfied: certifi>=2021.10.8 in c:\programdata\anaconda3\lib\site-packages (from selenium) (2022.9.14)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\programdata\anaconda3\lib\site-packages (from selenium) (1.26.11)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\dell\appdata\roaming\python\python39\site-packages (from selenium) (0.10.4)
Requirement already satisfied: sortedcontainers in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: outcome in c:\users\dell\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: attrs>=20.1.0 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\dell\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.1.3)
Requirement already satisfied: cffi>=1.14 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: sniffio in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: idna in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: wsproto>=0.14 in c:\users\dell\appdata\roaming\python\python39\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\programdata\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\dell\appdata\roaming\python\python39\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [2]:
import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By

import time

In [3]:
#Activating the chrome browser
driver=webdriver.Chrome()

In [4]:
#Opening the home page
driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos ")

In [5]:
#Creating empty list for different attributes
accquried_rank=[]
video_name=[]
artist_title=[]
upload_date=[]
views_total=[]

In [6]:
#Scrapping data for different attributes
rank_tags=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[1]')
for i in rank_tags:
    rank=i.text
    accquried_rank.append(rank)
    
name_tags=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[2]')
for i in name_tags:
    name=i.text
    video_name.append(name)
    
title_tags=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[3]')
for i in title_tags:
    title=i.text
    artist_title.append(title)
    
date_tags=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[5]')
for i in date_tags:
    date=i.text
    upload_date.append(date)
    
total_tags=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[4]')
for i in total_tags:
    total=i.text
    views_total.append(total)

In [7]:
#Checking length for all attributes
print(len(accquried_rank),len(video_name),len(artist_title),len(upload_date),len(views_total))

48 48 48 48 48

In [8]:
#Creating Dataframe
df=pd.DataFrame({'Rank':accquried_rank,'Name':video_name,'Title':artist_title,'Date':upload_date,'Total':views_total})
df

,Rank,Name,Title,Date,Total
0,1.,"""Baby Shark Dance""[6]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",13.48
1,2.,"""Despacito""[9]",Luis Fonsi,"January 12, 2017",8.28
2,3.,"""Johny Johny Yes Papa""[17]",LooLoo Kids - Nursery Rhymes and Children's Songs,"October 8, 2016",6.82
3,4.,"""Bath Song""[18]",Cocomelon - Nursery Rhymes,"May 2, 2018",6.45
4,5.,"""Shape of You""[19]",Ed Sheeran,"January 30, 2017",6.11
5,6.,"""See You Again""[22]",Wiz Khalifa,"April 6, 2015",6.05
6,7.,"""Wheels on the Bus""[27]",Cocomelon - Nursery Rhymes,"May 24, 2018",5.62
7,8.,"""Phonics Song with Two Words""[28]",ChuChu TV Nursery Rhymes & Kids Songs,"March 6, 2014",5.52
8,9.,"""Uptown Funk""[29]",Mark Ronson,"November 19, 2014",5.05
9,10.,"""Learning Colors – Colorful Eggs on a Farm""[30]",Miroshka TV,"February 27, 2018",4.99
10,11.,"""Gangnam Style""[31]",officialpsy,"July 15, 2012",4.92
11,12.,"""Masha and the Bear – Recipe for Disaster""[36]",Get Movies,"January 31, 2012",4.56
12,13.,"""Dame Tu Cosita""[37]",Ultra Records,"April 5, 2018",4.46
13,14.,"""Axel F""[38]",Crazy Frog,"June 16, 2009",4.09
14,15.,"""Sugar""[39]",Maroon 5,"January 14, 2015",3.95
15,16.,"""Counting Stars""[40]",OneRepublic,"May 31, 2013",3.89
16,17.,"""Roar""[41]",Katy Perry,"September 5, 2013",3.89
17,18.,"""Baa Baa Black Sheep""[42]",Cocomelon - Nursery Rhymes,"June 25, 2018",3.80
18,19.,"""Waka Waka (This Time for Africa)""[43]",Shakira,"June 4, 2010",3.75
19,20.,"""Sorry""[44]",Justin Bieber,"October 22, 2015",3.72
20,21.,"""Lakdi Ki Kathi""[45]",Jingle Toons,"June 14, 2018",3.71
21,22.,"""Thinking Out Loud""[46]",Ed Sheeran,"October 7, 2014",3.67
22,23.,"""Dark Horse""[47]",Katy Perry,"February 20, 2014",3.60
23,24.,"""Humpty the train on a fruits ride""[48]",Kiddiestv Hindi - Nursery Rhymes & Kids Songs,"January 26, 2018",3.58
24,25.,"""Perfect""[49]",Ed Sheeran,"November 9, 2017",3.56
25,26.,"""Let Her Go""[50]",Passenger,"July 25, 2012",3.53
26,27.,"""Faded""[51]",Alan Walker,"December 3, 2015",3.53
27,28.,"""Girls Like You""[52]",Maroon 5,"May 31, 2018",3.50
28,29.,"""Shree Hanuman Chalisa""[53]",T-Series Bhakti Sagar,"May 10, 2011",3.48
29,30.,"""Lean On""[54]",Major Lazer Official,"March 22, 2015",3.48
30,"""Baby Shark Dance""[6]",Pinkfong Baby Shark - Kids' Songs & Stories,"7,046,700,000","November 2, 2020","June 17, 2016"
31,"""Despacito""[9]",Luis Fonsi,"2,993,700,000","August 4, 2017","January 12, 2017"
32,"""See You Again""[22]",Wiz Khalifa,"2,894,000,000","July 10, 2017","April 6, 2015"
33,"""Gangnam Style""⁂[31]",Psy,"803,700,000","November 24, 2012","July 15, 2012"
34,"""Baby""*[66]",Justin Bieber,"245,400,000","July 16, 2010","February 19, 2010"
35,"""Bad Romance""[70]",Lady Gaga,"178,400,000","April 14, 2010","November 24, 2009"
36,"""Charlie Bit My Finger""‡[74]",HDCYT,"128,900,000","October 25, 2009","May 22, 2007"
37,"""Evolution of Dance""[77]",Judson Laipply,"118,900,000","May 2, 2009","April 6, 2006"
38,"""Girlfriend""‡[79][80]",RCA Records,"92,600,000","July 17, 2008","February 27, 2007"
39,"""Evolution of Dance""[77]",Judson Laipply,"78,400,000","March 15, 2008","April 6, 2006"
40,"""Music Is My Hot Hot Sex""‡[85]",CLARUSBARTEL72,"76,600,000","March 1, 2008","April 9, 2007"
41,"""Evolution of Dance""*[77]",Judson Laipply,"10,600,000","May 19, 2006","April 6, 2006"
42,"""Pokémon Theme Music Video""‡[90]",Smosh,"4,300,000","March 12, 2006","November 28, 2005"
43,"""Myspace – The Movie""‡[95][96]",eggtea,"2,700,000","February 18, 2006","January 31, 2006"
44,"""Phony Photo Booth""‡[99]",mugenized,"3,400,000","January 21, 2006","December 1, 2005"
45,"""The Chronic of Narnia Rap""‡[105]",youtubedude,"2,300,000","January 9, 2006","December 18, 2005"
46,"""Ronaldinho: Touch of Gold""‡*[108]",Nikesoccer,"255,000","October 31, 2005","October 21, 2005"
47,"""I/O Brush""‡*[114]",larfus,"247,000","October 29, 2005","October 5, 2005"

In [9]:
driver.close()

2. Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Series
B) Place
C) Date
D) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [10]:
!pip install selenium

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: selenium in c:\users\dell\appdata\roaming\python\python39\site-packages (4.12.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\dell\appdata\roaming\python\python39\site-packages (from selenium) (0.10.4)
Requirement already satisfied: trio~=0.17 in c:\users\dell\appdata\roaming\python\python39\site-packages (from selenium) (0.22.2)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\programdata\anaconda3\lib\site-packages (from selenium) (1.26.11)
Requirement already satisfied: certifi>=2021.10.8 in c:\programdata\anaconda3\lib\site-packages (from selenium) (2022.9.14)
Requirement already satisfied: attrs>=20.1.0 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\dell\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.1.3)
Requirement already satisfied: sniffio in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: sortedcontainers in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: cffi>=1.14 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: outcome in c:\users\dell\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: idna in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: wsproto>=0.14 in c:\users\dell\appdata\roaming\python\python39\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\programdata\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\dell\appdata\roaming\python\python39\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [11]:
import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By

import time

In [12]:
#Activating the chrome browser
driver=webdriver.Chrome()

In [13]:
#Opening the home page
driver.get("https://www.bcci.tv/.")

In [14]:
#Clicking on fixtures and result
fixtures=driver.find_element(By.XPATH,"/html/body/header/div[3]/div[1]/ul/div[1]/a[2]")
fixtures.click()

In [15]:
#Creating empty list for different attributes
series_title=[]
place_name=[]
performance_date=[]
time_performed=[]

In [16]:
#Scrapping data for different attributes
title_tags=driver.find_elements(By.XPATH,'//h5[@class="match-tournament-name ng-binding"]')
for i in title_tags:
    title=i.text
    series_title.append(title)
    
name_tags=driver.find_elements(By.XPATH,'//div[@class="match-place ng-scope"]')
for i in name_tags:
    name=i.text
    place_name.append(name)
    
date_tags=driver.find_elements(By.XPATH,'//div[@class="match-dates ng-binding"]')
for i in date_tags:
    date=i.text
    performance_date.append(date)
    
performed_tags=driver.find_elements(By.XPATH,'//div[@class="match-time no-margin ng-binding"]')
for i in performed_tags:
    performed=i.text
    time_performed.append(performed)

In [17]:
#Checking length for all attributes
print(len(series_title),len(place_name),len(performance_date),len(time_performed))

211 211 211 211

In [18]:
#Creating dataframe
df=pd.DataFrame({'Title':series_title,'Name':place_name,'Performance':performance_date,'Performed':time_performed})
df

,Title,Name,Performance,Performed
0,ICC MENS WORLD CUP 2023,"Narendra Modi Stadium, Ahmedabad","14 OCTOBER, 2023",2:00 PM IST
1,ICC MENS WORLD CUP 2023,"Maharashtra Cricket Association Stadium, Pune","19 OCTOBER, 2023",2:00 PM IST
2,ICC MENS WORLD CUP 2023,"Himachal Pradesh Cricket Association Stadium, ...","22 OCTOBER, 2023",2:00 PM IST
3,ICC MENS WORLD CUP 2023,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,"29 OCTOBER, 2023",2:00 PM IST
4,ICC MENS WORLD CUP 2023,"Wankhede Stadium, Mumbai","2 NOVEMBER, 2023",2:00 PM IST
...,...,...,...,...
206,ASIA CUP 2022,"Dubai International Cricket Stadium, Dubai","6 SEPTEMBER, 2022",7:30 PM IST
207,ASIA CUP 2022,"Dubai International Cricket Stadium, Dubai","4 SEPTEMBER, 2022",7:30 PM IST
208,NEW ZEALAND A TOUR OF INDIA,"M.Chinnaswamy Stadium, Bangalore","1 SEPTEMBER, 2022",9:30 AM IST
209,ASIA CUP 2022,"Dubai International Cricket Stadium, Dubai","31 AUGUST, 2022",7:30 PM IST
210,ASIA CUP 2022,"Dubai International Cricket Stadium, Dubai","28 AUGUST, 2022",7:30 PM IST

In [19]:
driver.close()

5. Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/ You have to find the
following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
 Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [14]:
!pip install selenium

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: selenium in c:\users\dell\appdata\roaming\python\python39\site-packages (4.12.0)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\programdata\anaconda3\lib\site-packages (from selenium) (1.26.11)
Requirement already satisfied: certifi>=2021.10.8 in c:\programdata\anaconda3\lib\site-packages (from selenium) (2022.9.14)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\dell\appdata\roaming\python\python39\site-packages (from selenium) (0.10.4)
Requirement already satisfied: trio~=0.17 in c:\users\dell\appdata\roaming\python\python39\site-packages (from selenium) (0.22.2)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\dell\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.1.3)
Requirement already satisfied: attrs>=20.1.0 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: cffi>=1.14 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: outcome in c:\users\dell\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: sortedcontainers in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: sniffio in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: idna in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: wsproto>=0.14 in c:\users\dell\appdata\roaming\python\python39\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\programdata\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\dell\appdata\roaming\python\python39\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [15]:
import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By

import time

In [16]:
#Activating the chrome browser
driver=webdriver.Chrome()

In [17]:
#Opening the home page
driver.get("https:/www.billboard.com/")

In [19]:
#Clicking to open the list
search=driver.find_element(By.CLASS_NAME,"lrv-a-crop-1x1")
search.click()

In [20]:
#Creating empty list for different attributes
song_title=[]
artist_name=[]
last_weekRank=[]
peak_rank=[]
weeks_onBoard=[]

In [21]:
#Scraping data for different attributes
title_tags=driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]/ul/li/h3')
for i in title_tags:
    title=i.text
    song_title.append(title)
    
name_tags=driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]/ul/li[1]/span')
for i in name_tags:
    name=i.text
    artist_name.append(name)
    
weekRank_tags=driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]/ul/li[4]/span')
for i in weekRank_tags:
    weekRank=i.text
    last_weekRank.append(weekRank)
    
rank_tags=driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]/ul/li[5]/span')
for i in rank_tags:
    rank=i.text
    peak_rank.append(rank)
    
onBoard_tags=driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]/ul/li[6]/span')
for i in onBoard_tags:
    onBoard=i.text
    weeks_onBoard.append(onBoard)

In [22]:
#checking length of all attributes
print(len(song_title),len(artist_name),len(last_weekRank),len(peak_rank),len(weeks_onBoard))

100 100 100 100 100

In [23]:
#creating data frame
df=pd.DataFrame({'Title':song_title,'Name':artist_name,'WeekRank':last_weekRank,'Rank':peak_rank,'OnBoard':weeks_onBoard})
df

,Title,Name,WeekRank,Rank,OnBoard
0,First Person Shooter,Drake Featuring J. Cole,-,1,1
1,IDGAF,Drake Featuring Yeat,-,2,1
2,Virginia Beach,Drake,-,3,1
3,Paint The Town Red,Doja Cat,1,1,10
4,Calling For You,Drake Featuring 21 Savage,-,5,1
...,...,...,...,...,...
95,God Gave Me A Girl,Russell Dickerson,90,90,2
96,Y Lloro,Junior H,-,97,1
97,Telekinesis,Travis Scott Featuring SZA & Future,72,26,11
98,Seven,Jung Kook Featuring Latto,57,1,13
99,Stars Like Confetti,Dustin Lynch,89,89,2

In [24]:
driver.close()

6. Scrape the details of Highest selling novels.
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre
 Url - https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare

In [31]:
!pip install selenium

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: selenium in c:\users\dell\appdata\roaming\python\python39\site-packages (4.12.0)
Requirement already satisfied: certifi>=2021.10.8 in c:\programdata\anaconda3\lib\site-packages (from selenium) (2022.9.14)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\programdata\anaconda3\lib\site-packages (from selenium) (1.26.11)
Requirement already satisfied: trio~=0.17 in c:\users\dell\appdata\roaming\python\python39\site-packages (from selenium) (0.22.2)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\dell\appdata\roaming\python\python39\site-packages (from selenium) (0.10.4)
Requirement already satisfied: sortedcontainers in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: cffi>=1.14 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\dell\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.1.3)
Requirement already satisfied: attrs>=20.1.0 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: sniffio in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: outcome in c:\users\dell\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\dell\appdata\roaming\python\python39\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\programdata\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\dell\appdata\roaming\python\python39\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [32]:
import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By

import time

In [33]:
#Activating the chrome browser
driver=webdriver.Chrome()

In [34]:
#Opening the home page
driver.get(" https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare")

In [36]:
#Creating empty list for different attributes
novel_rank=[]
name_title=[]
author_label=[]
vol_sales=[]
publisher_OfNovel=[]
genre_support=[]

In [37]:
#Scrapping data for different attributes
rank_tags=driver.find_elements(By.XPATH,'//div[@class="embed block"]/table/tbody/tr/td[1]')
for i in rank_tags:
    rank=i.text
    novel_rank.append(rank)
    
title_tags=driver.find_elements(By.XPATH,'//div[@class="embed block"]/table/tbody/tr/td[2]')
for i in title_tags:
    title=i.text
    name_title.append(title)
    
label_tags=driver.find_elements(By.XPATH,'//div[@class="embed block"]/table/tbody/tr/td[3]')
for i in label_tags:
    label=i.text
    author_label.append(label)
    
sales_tags=driver.find_elements(By.XPATH,'//div[@class="embed block"]/table/tbody/tr/td[4]')
for i in sales_tags:
    sales=i.text
    vol_sales.append(sales)
    
OfNovel_tags=driver.find_elements(By.XPATH,'//div[@class="embed block"]/table/tbody/tr/td[5]')
for i in OfNovel_tags:
    OfNovel=i.text
    publisher_OfNovel.append(OfNovel)
    
support_tags=driver.find_elements(By.XPATH,'//div[@class="embed block"]/table/tbody/tr/td[6]')
for i in support_tags:
    support=i.text
    genre_support.append(support)

In [38]:
#Checking lengths of all attributes
print(len(novel_rank),len(name_title),len(author_label),len(vol_sales),len(publisher_OfNovel),len(genre_support))

100 100 100 100 100 100

In [39]:
#creating data frame
df=pd.DataFrame({'Rank':novel_rank,'Title':name_title,'Label':author_label,'Sales':vol_sales,'OfNovel':publisher_OfNovel,'Support':genre_support})
df

,Rank,Title,Label,Sales,OfNovel,Support
0,1,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,2,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,3,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,4,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,5,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...,...
95,96,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,97,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,98,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,99,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,100,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [40]:
driver.close()

7. Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/ You have
to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [41]:
!pip install selenium

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: selenium in c:\users\dell\appdata\roaming\python\python39\site-packages (4.12.0)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\programdata\anaconda3\lib\site-packages (from selenium) (1.26.11)
Requirement already satisfied: trio~=0.17 in c:\users\dell\appdata\roaming\python\python39\site-packages (from selenium) (0.22.2)
Requirement already satisfied: certifi>=2021.10.8 in c:\programdata\anaconda3\lib\site-packages (from selenium) (2022.9.14)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\dell\appdata\roaming\python\python39\site-packages (from selenium) (0.10.4)
Requirement already satisfied: idna in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: attrs>=20.1.0 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: cffi>=1.14 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\dell\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.1.3)
Requirement already satisfied: sniffio in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: outcome in c:\users\dell\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: sortedcontainers in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\dell\appdata\roaming\python\python39\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\programdata\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\dell\appdata\roaming\python\python39\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [42]:
import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By

import time

In [43]:
#Activating the chrome browser
driver=webdriver.Chrome()

In [44]:
#Opening the home page
driver.get("https://www.imdb.com/list/ls095964455/")

In [45]:
#Creating empty list for different attributes
movie_name=[]
span_year=[]
support_genre=[]
run_time=[]
given_ratings=[]
accquired_votes=[]

In [46]:
#Scrapping data for different attributes
name_tags=driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/h3/a')
for i in name_tags:
    name=i.text
    movie_name.append(name)
    
year_tags=driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/h3/span[2]')
for i in year_tags:
    year=i.text
    span_year.append(year)
    
genre_tags=driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/p/span[5]')
for i in genre_tags:
    genre=i.text
    support_genre.append(genre)
    
time_tags=driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/p/span[3]')
for i in time_tags:
    time=i.text
    run_time.append(time)
    
ratings_tags=driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/div/div[1]')
for i in ratings_tags:
    ratings=i.text
    given_ratings.append(ratings)
    
votes_tags=driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/p[4]/span[2]')
for i in votes_tags:
    votes=i.text
    accquired_votes.append(votes)

In [47]:
#Checking lengths of all attributes
print(len(movie_name),len(span_year),len(support_genre),len(run_time),len(given_ratings),len(accquired_votes))

100 100 100 100 100 100

In [48]:
#Creating Data frame
df=pd.DataFrame({'Name':movie_name,'Year':span_year,'Genre':support_genre,'Time':run_time,'Ratings':given_ratings,'Votes':accquired_votes})
df

,Name,Year,Genre,Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,213,614"
1,Stranger Things,(2016–2025),"Drama, Fantasy, Horror",51 min,8.7,"1,283,368"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"1,050,453"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"308,643"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"267,580"
...,...,...,...,...,...,...
95,Reign,(2013– ),Drama,42 min,7.5,"52,961"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"65,033"
97,Criminal Minds,(2005– ),"Crime, Drama, Mystery",42 min,8.1,"211,943"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7,"44,115"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"270,233"

8. Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/ You
have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute G) Year
 Note: - from the home page you have to go to the Show All Dataset page through code.

In [31]:
!pip install selenium

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: selenium in c:\users\dell\appdata\roaming\python\python39\site-packages (4.12.0)
Requirement already satisfied: trio~=0.17 in c:\users\dell\appdata\roaming\python\python39\site-packages (from selenium) (0.22.2)
Requirement already satisfied: certifi>=2021.10.8 in c:\programdata\anaconda3\lib\site-packages (from selenium) (2022.9.14)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\dell\appdata\roaming\python\python39\site-packages (from selenium) (0.10.4)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\programdata\anaconda3\lib\site-packages (from selenium) (1.26.11)
Requirement already satisfied: idna in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: sortedcontainers in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: sniffio in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: outcome in c:\users\dell\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\dell\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.1.3)
Requirement already satisfied: attrs>=20.1.0 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: cffi>=1.14 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\dell\appdata\roaming\python\python39\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\programdata\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\dell\appdata\roaming\python\python39\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [32]:
import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By

import time

In [33]:
#Activating the chrome browser
driver=webdriver.Chrome()

In [34]:
#Opening the home page
driver.get(" https://archive.ics.uci.edu/")

In [35]:
#Clicking on Search Button-
search=driver.find_element(By.XPATH,"/html/body/div/div[1]/div[1]/main/div/div[1]/div/div/div/a[1]")
search.click()

In [36]:
#Click on expand all button-
search=driver.find_element(By.CLASS_NAME,"swap")
search.click()

In [37]:
#Creating empty list for different attributes:-
dataset_name=[]
data_typee=[]
given_task=[]
attribute_title=[]
numberOf_instances=[]
total_attributes=[]
mentioned_year=[]

In [38]:
#scraping data for different attributes from different pages:-
start=0
end=65
for page in range(start,end):
    name=driver.find_elements(By.XPATH,'//div[@class="relative col-span-8 sm:col-span-7"]/h2/a')
    for i in name[0:10]:
        dataset_name.append(i.text)
    typee=driver.find_elements(By.XPATH,'//div[@class="grid grid-cols-8 overflow-x-auto"]/table/tbody/tr/td[2]')
    for i in typee[0:10]:
        data_typee.append(i.text)
    task=driver.find_elements(By.XPATH,'//div[@class="relative col-span-8 sm:col-span-7"]/div/div[1]')
    for i in task[0:10]:
        given_task.append(i.text)
    title=driver.find_elements(By.XPATH,'//div[@class="grid grid-cols-8 overflow-x-auto"]/table/tbody/tr/td[1]')
    for i in title[0:10]:
        attribute_title.append(i.text)
    instances=driver.find_elements(By.XPATH,'//div[@class="relative col-span-8 sm:col-span-7"]/div/div[3]/span')
    for i in instances[0:10]:
        numberOf_instances.append(i.text)
    attributes=driver.find_elements(By.XPATH,'//div[@class="relative col-span-8 sm:col-span-7"]/div/div[4]/span')
    for i in attributes[0:10]:
        total_attributes.append(i.text)
    year=driver.find_elements(By.XPATH,'//div[@class="grid grid-cols-8 overflow-x-auto"]/table/tbody/tr/td[3]')
    for i in year[0:10]:
        mentioned_year.append(i.text)
    next_button=driver.find_elements(By.XPATH,'//div[@class="btn-group"]/button[2]')

In [39]:
#checking length for all attributes-
print(len(dataset_name),len(data_typee),len(given_task),len(attribute_title),len(numberOf_instances),len(total_attributes),len(mentioned_year))

650 650 650 650 650 650 650

In [40]:
# Creating Dataframe-
df=pd.DataFrame({'Name':dataset_name,'Typee':data_typee,'Task':given_task,'Title':attribute_title,'Instances':numberOf_instances,'Attributes':total_attributes,'Year':mentioned_year})
df

,Name,Typee,Task,Title,Instances,Attributes,Year
0,Iris,Real,Classification,Life Science,150 Instances,4 Features,7/1/1988
1,Heart Disease,"Categorical, Integer, Real",Classification,Life Science,303 Instances,13 Features,7/1/1988
2,Adult,"Categorical, Integer",Classification,Social Science,48.84K Instances,14 Features,5/1/1996
3,Wine,"Integer, Real",Classification,Physical Science,178 Instances,13 Features,7/1/1991
4,Breast Cancer Wisconsin (Diagnostic),Real,Classification,Life Science,569 Instances,30 Features,11/1/1995
...,...,...,...,...,...,...,...
645,Diabetes,"Categorical, Integer",,Life Science,,20 Features,N/A
646,Dry Bean Dataset,"Integer, Real",Classification,Computer Science,13.61K Instances,16 Features,9/14/2020
647,Car Evaluation,Categorical,Classification,Other,1.73K Instances,6 Features,6/1/1997
648,Rice (Cammeo and Osmancik),Real,Classification,Computer Science,3.81K Instances,8 Features,10/6/2019
649,Wine Quality,Real,"Classification, Regression",Business,4.9K Instances,12 Features,10/7/2009

In [41]:
driver.close()